CI: Use Clang 18 (#132)
* clang-tidy

* update fmt

* clang 18

* format using clang-format-18

* ???

without default:
error: 'switch' missing 'default' label [-Werror,-Wswitch-default]
with default:
error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]

* we have to disable one of the switch warnings

see https://github.com/nlohmann/json/discussions/3539

* switch to latest docker-cpp-build